resume: null
epochs: 20
mb_size: 1470
accum_steps: null
grad_clip: null
shuffle_windows: false
subset_frac: 0.0001
exclude_vars: []
use_foundation: null
carry_years: '1'
lr: 9.0e-05
scheduler: cosine_wr
sched_t0: epoch
sched_tmult: 2
eta_min: 9.0e-06
validation_frequency: 1.0
validation_size: 0.6
num_workers: 8
job_name: debug_delta_and_carry
log_batches_per_rank: false
loss_type: mse
use_mass_balances: false
water_balance_weight: 0.0
npp_balance_weight: 0.0
nbp_balance_weight: 0.0
carbon_partition_weight: 0.0
nbp_delta_ctotal_weight: 0.0
early_stop: true
early_stop_patience: 3
early_stop_min_delta: 0.0
early_stop_warmup_epochs: 0
ckpt_every_epochs: 1
keep_last: 5
delta: true
