resume: null
epochs: 30
mb_size: 2940
accum_steps: null
grad_clip: null
shuffle_windows: true
subset_frac: null
exclude_vars: []
use_foundation: /Net/Groups/BGI/people/ecathain/TRENDY_Emulator_Scripts/NewModel/pipeline/1.train/runs/saved_checkpoints/transfer_learning/avh15c1_lai/second_train_to_epoch_22/checkpoints/best.pt
train_only: false
test_only: false
delta_luh: false
lr: 9.0e-05
scheduler: cosine_wr
sched_t0: epoch
sched_tmult: 2
eta_min: 9.0e-06
val_freq: 1.0
val_frac: 0.7
test_frac: 0.5
num_workers: 8
job_name: tl_lai_3
log_batches_per_rank: false
loss_type: mse
use_mass_balances: false
water_balance: 0.0
npp_balance: 0.0
nbp_balance: 0.0
carbon_partition_balance: 0.0
nbp_d_ctotal_balance: 0.0
early_stop: true
early_stop_patience: 8
early_stop_min_delta: 0.0
early_stop_warmup_epochs: 0
ckpt_every_epochs: 1
keep_last: 5
transfer_learn: true
transfer_learn_vars:
- lai_avh15c1
transfer_learn_years: 1982-2018
scan_finite: false
var_weights: lai=3
