resume: null
epochs: 2
mb_size: 2940
accum_steps: null
grad_clip: null
shuffle_windows: true
subset_frac: 0.0001
exclude_vars: []
use_foundation: null
train_only: false
test_only: false
delta_luh: true
lr: 9.0e-05
scheduler: cosine_wr
sched_t0: epoch
sched_tmult: 2
eta_min: 9.0e-06
val_freq: 1.0
val_frac: 0.7
test_frac: 0.5
num_workers: 8
job_name: delta_luh
log_batches_per_rank: false
loss_type: mse
use_mass_balances: false
water_balance_weight: 0.0
npp_balance_weight: 0.0
nbp_balance_weight: 0.0
carbon_partition_weight: 0.0
nbp_delta_ctotal_weight: 0.0
early_stop: true
early_stop_patience: 10
early_stop_min_delta: 0.0
early_stop_warmup_epochs: 0
ckpt_every_epochs: 1
keep_last: 5
transfer_learn: false
transfer_learn_vars:
- lai_avh15c1
transfer_learn_years: 1981-2019
scan_finite: false
