resume: null
epochs: 60
mb_size: 2940
accum_steps: null
grad_clip: null
shuffle_windows: true
subset_frac: null
exclude_vars:
- pre_rolling_mean
- tmp_rolling_mean
- spfh_rolling_mean
- tmax_rolling_mean
- tmin_rolling_mean
use_foundation: null
lr: 9.0e-05
scheduler: cosine_wr
sched_t0: epoch
sched_tmult: 2
eta_min: 9.0e-06
validation_frequency: 1.0
validation_size: 0.6
num_workers: 8
job_name: no_rolling_mean
log_batches_per_rank: false
loss_type: mse
use_mass_balances: false
water_balance_weight: 0.0
npp_balance_weight: 0.0
nbp_balance_weight: 0.0
carbon_partition_weight: 0.0
nbp_delta_ctotal_weight: 0.0
early_stop: true
early_stop_patience: 10
early_stop_min_delta: 0.0
early_stop_warmup_epochs: 30
ckpt_every_epochs: 1
keep_last: 5
