resume: null
epochs: 30
mb_size: 2940
accum_steps: null
grad_clip: null
shuffle_windows: true
subset_frac: 0.0001
exclude_vars: []
use_foundation: /Net/Groups/BGI/people/ecathain/TRENDY_Emulator_Scripts/NewModel/pipeline/1.train/runs/saved_checkpoints/base_model/base_model_new_loss/checkpoints/best.pt
train_only: false
test_only: false
delta_luh: false
lr: 9.0e-05
scheduler: cosine_wr
sched_t0: epoch
sched_tmult: 2
eta_min: 9.0e-06
val_freq: 1.0
val_frac: 0.7
test_frac: 0.5
num_workers: 8
job_name: tiny_mb_test
log_batches_per_rank: false
loss_type: mse
use_mass_balances: true
water_balance: 0.0
npp_balance: 1.0
nbp_balance: 1.0
carbon_partition_balance: 0.1
nbp_d_ctotal_balance: 0.1
early_stop: true
early_stop_patience: 10
early_stop_min_delta: 0.0
early_stop_warmup_epochs: 0
ckpt_every_epochs: 1
keep_last: 5
transfer_learn: false
transfer_learn_vars:
- lai_avh15c1
transfer_learn_years: 1981-2019
scan_finite: false
