resume: null
epochs: 60
mb_size: 2940
eval_mb_size: 1470
accum_steps: null
grad_clip: null
shuffle_windows: false
subset_frac: null
exclude_vars: []
use_foundation: /Net/Groups/BGI/people/ecathain/TRENDY_Emulator_Scripts/NewModel/checkpoints/base_model/checkpoints/best.pt
train_only: false
test_only: false
val_only: false
prefetch_factor: 1
val_prefetch_factor: 1
lr: 9.0e-05
scheduler: cosine_wr
sched_t0: epoch
sched_tmult: 2
eta_min: 9.0e-06
val_freq: 1.0
val_frac: 0.5
test_frac: 0.5
num_workers: 4
job_name: carry_1_train
log_batches_per_rank: false
loss_type: mse
use_mass_balances: false
water_balance_weight: 0.0
npp_balance_weight: 0.0
nbp_balance_weight: 0.0
carbon_partition_weight: 0.0
nbp_delta_ctotal_weight: 0.0
early_stop: true
early_stop_patience: 10
early_stop_min_delta: 0.0
early_stop_warmup_epochs: 0
ckpt_every_epochs: 1
keep_last: 5
carry_years: '1'
carry_granularity: annual
block_locs: 70
scan_finite: false
