resume: null
epochs: 20
mb_size: 2940
accum_steps: null
grad_clip: null
shuffle_windows: true
subset_frac: 1.0
exclude_vars:
- pre_rolling_mean
- tmp_rolling_mean
- spfh_rolling_mean
- tmax_rolling_mean
- tmin_rolling_mean
use_foundation: /Net/Groups/BGI/people/ecathain/TRENDY_Emulator_Scripts/NewModel/scripts/a_pipeline/1.train/runs/saved_checkpoints/base_model/old_loss/base_model_no_rolling_mean_old_loss/checkpoints/best.pt
train_only: false
test_only: false
lr: 9.0e-05
scheduler: cosine_wr
sched_t0: epoch
sched_tmult: 2
eta_min: 9.0e-06
val_freq: 1.0
val_frac: 0.5
test_frac: null
num_workers: 8
job_name: train_test
log_batches_per_rank: false
loss_type: mse
use_mass_balances: false
water_balance_weight: 0.0
npp_balance_weight: 0.0
nbp_balance_weight: 0.0
carbon_partition_weight: 0.0
nbp_delta_ctotal_weight: 0.0
early_stop: true
early_stop_patience: 7
early_stop_min_delta: 0.0
early_stop_warmup_epochs: 0
ckpt_every_epochs: 1
keep_last: 5
delta: false
carry_years:
- '0'
carry_granularity: annual
scan_finite: false
