resume: null
epochs: 1
mb_size: 1470
accum_steps: null
grad_clip: null
shuffle_windows: true
subset_frac: 0.0001
exclude_vars: []
use_foundation: /Net/Groups/BGI/people/ecathain/TRENDY_Emulator_Scripts/NewModel/pipeline/1.train/runs/saved_checkpoints/base_model/new_loss/base_model_new_loss/checkpoints/best.pt
train_only: false
test_only: false
lr: 9.0e-05
scheduler: cosine_wr
sched_t0: epoch
sched_tmult: 2
eta_min: 9.0e-06
val_freq: 0.5
val_frac: 0.5
test_frac: null
num_workers: 8
job_name: test_core_branch
log_batches_per_rank: false
loss_type: mse
use_mass_balances: false
water_balance_weight: 0.0
npp_balance_weight: 0.0
nbp_balance_weight: 0.0
carbon_partition_weight: 0.0
nbp_delta_ctotal_weight: 0.0
early_stop: true
early_stop_patience: 7
early_stop_min_delta: 0.0
early_stop_warmup_epochs: 0
ckpt_every_epochs: 1
keep_last: 5
transfer_learn: true
transfer_learn_vars:
- lai_avh15c1
transfer_learn_years: 1982-2018
scan_finite: false
